// Copyright 2023 The rust-ggstd authors.
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//! Package rand implements pseudo-random number generators unsuitable for
//! security-sensitive work.
//!
//! Random numbers are generated by a [Source], usually wrapped in a [Rand].
//! Both types should be used by a single goroutine at a time: sharing among
//! multiple goroutines requires some kind of synchronization.
//!
//! Top-level functions, such as [float64] and [int],
//! are safe for concurrent use by multiple goroutines.
//!
//! This package's outputs might be easily predictable regardless of how it's
//! seeded. For random numbers suitable for security-sensitive work, see the
//! crypto/rand package.

mod rand;
mod rng;

#[allow(deprecated)]
pub use rand::seed;
pub use rand::{
    float32, float64, int, int31, int31n, int63n, intn, new_source, norm_float64, Rand, Source,
};

#[cfg(test)]
mod rand_test;
