name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cargo build
      run: cargo build --verbose
    - name: cargo test
      run: cargo test --verbose
    - name: cargo test --release
      run: cargo test --verbose --release
    - name: cargo clippy
      run: cargo clippy
